import { readFile } from 'node:fs/promises';
import { extname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Script } from 'node:vm';

import type { EelZapClient } from '../client';

export type FileNameCasing = 'kebab' | 'camel' | 'pascal' | 'snake';
export type FolderNameCasing = FileNameCasing;
export type TypeNameCasing = 'pascal' | 'camel';

export interface EelZapCodegenConfig {
  apiKey?: string;
  baseUrl?: string;
  outputDir?: string;
  writeFiles?: boolean;
  collections?: boolean;
  documents?: boolean;
  includeCollections?: string[];
  includeDocuments?: string[];
  excludeCollections?: string[];
  excludeDocuments?: string[];
  fileNameCasing?: FileNameCasing;
  folderNameCasing?: FolderNameCasing;
  typeNameCasing?: TypeNameCasing;
  addFieldComments?: boolean;
  generateIndex?: boolean;
  includeSeo?: boolean;
  includeMeta?: boolean;
  header?: string;
  client?: EelZapClient;
}

export interface ResolvedCodegenConfig extends EelZapCodegenConfig {
  outputDir: string;
  writeFiles: boolean;
  collections: boolean;
  documents: boolean;
  includeCollections: string[];
  includeDocuments: string[];
  excludeCollections: string[];
  excludeDocuments: string[];
  fileNameCasing: FileNameCasing;
  folderNameCasing: FolderNameCasing;
  typeNameCasing: TypeNameCasing;
  addFieldComments: boolean;
  generateIndex: boolean;
  includeSeo: boolean;
  includeMeta: boolean;
  header: string;
}

export interface CliFlags {
  apiKey?: string;
  baseUrl?: string;
  outputDir?: string;
  collections?: boolean;
  documents?: boolean;
  include?: string[];
  exclude?: string[];
  addFieldComments?: boolean;
  includeSeo?: boolean;
  includeMeta?: boolean;
  generateIndex?: boolean;
  dryRun?: boolean;
  verbose?: boolean;
  configPath?: string;
  help?: boolean;
  version?: boolean;
}

export interface ConfigLoadResult {
  config: EelZapCodegenConfig;
  path: string | null;
}

const CONFIG_FILE_NAMES = [
  'eelzap.config.ts',
  'eelzap.config.js',
  'eelzap.config.mjs',
  'eelzap.config.json',
  '.eelzaprc.json',
] as const;

export const DEFAULT_CODEGEN_CONFIG: ResolvedCodegenConfig = {
  outputDir: 'types/eel-zap',
  writeFiles: false,
  collections: true,
  documents: true,
  includeCollections: [],
  includeDocuments: [],
  excludeCollections: [],
  excludeDocuments: [],
  fileNameCasing: 'kebab',
  folderNameCasing: 'kebab',
  typeNameCasing: 'pascal',
  addFieldComments: true,
  generateIndex: true,
  includeSeo: true,
  includeMeta: true,
  header: '/* Auto-generated by @8ux-co/eelzap-api-sdk-ts codegen - DO NOT EDIT */',
};

export function getSupportedConfigFileNames(): readonly string[] {
  return CONFIG_FILE_NAMES;
}

export async function discoverConfigPath(cwd: string): Promise<string | null> {
  for (const fileName of CONFIG_FILE_NAMES) {
    const filePath = resolve(cwd, fileName);
    try {
      await readFile(filePath, 'utf8');
      return filePath;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }
  }

  return null;
}

export async function loadConfigFile(filePath: string): Promise<EelZapCodegenConfig> {
  const extension = extname(filePath).toLowerCase();

  if (extension === '.json') {
    const raw = await readFile(filePath, 'utf8');
    return parseJsonConfig(raw, filePath);
  }

  if (extension === '.js' || extension === '.mjs') {
    const module = (await import(pathToFileURL(filePath).href)) as {
      default?: EelZapCodegenConfig;
    };
    return module.default ?? {};
  }

  if (extension === '.ts') {
    const raw = await readFile(filePath, 'utf8');
    return parseTypeScriptConfig(raw, filePath);
  }

  throw new Error(`Unsupported config file extension for ${filePath}.`);
}

export async function loadConfig(cwd: string, explicitPath?: string): Promise<ConfigLoadResult> {
  const discoveredPath = explicitPath ? resolve(cwd, explicitPath) : await discoverConfigPath(cwd);

  if (!discoveredPath) {
    return {
      config: {},
      path: null,
    };
  }

  return {
    config: await loadConfigFile(discoveredPath),
    path: discoveredPath,
  };
}

export function resolveCodegenConfig(
  fileConfig: EelZapCodegenConfig,
  flags: CliFlags,
  env: NodeJS.ProcessEnv,
): ResolvedCodegenConfig {
  const collections =
    flags.collections ??
    envBoolean(env.EELZAP_CODEGEN_COLLECTIONS) ??
    fileConfig.collections ??
    DEFAULT_CODEGEN_CONFIG.collections;
  const documents =
    flags.documents ??
    envBoolean(env.EELZAP_CODEGEN_DOCUMENTS) ??
    fileConfig.documents ??
    DEFAULT_CODEGEN_CONFIG.documents;

  return {
    ...DEFAULT_CODEGEN_CONFIG,
    ...fileConfig,
    apiKey: flags.apiKey ?? env.EELZAP_API_KEY ?? fileConfig.apiKey,
    baseUrl: flags.baseUrl ?? env.EELZAP_BASE_URL ?? fileConfig.baseUrl,
    outputDir:
      flags.outputDir ??
      env.EELZAP_CODEGEN_OUTPUT_DIR ??
      fileConfig.outputDir ??
      DEFAULT_CODEGEN_CONFIG.outputDir,
    writeFiles: flags.dryRun ? false : (fileConfig.writeFiles ?? DEFAULT_CODEGEN_CONFIG.writeFiles),
    collections,
    documents,
    includeCollections: normalizeStringArray(
      flags.include ?? envList(env.EELZAP_CODEGEN_INCLUDE) ?? fileConfig.includeCollections,
    ),
    includeDocuments: normalizeStringArray(
      flags.include ?? envList(env.EELZAP_CODEGEN_INCLUDE) ?? fileConfig.includeDocuments,
    ),
    excludeCollections: normalizeStringArray(
      flags.exclude ?? envList(env.EELZAP_CODEGEN_EXCLUDE) ?? fileConfig.excludeCollections,
    ),
    excludeDocuments: normalizeStringArray(
      flags.exclude ?? envList(env.EELZAP_CODEGEN_EXCLUDE) ?? fileConfig.excludeDocuments,
    ),
    fileNameCasing:
      flagsCasing(flags, 'fileNameCasing') ??
      envFileCasing(env.EELZAP_CODEGEN_FILE_CASING) ??
      fileConfig.fileNameCasing ??
      DEFAULT_CODEGEN_CONFIG.fileNameCasing,
    folderNameCasing:
      flagsCasing(flags, 'folderNameCasing') ??
      envFileCasing(env.EELZAP_CODEGEN_FOLDER_CASING) ??
      fileConfig.folderNameCasing ??
      DEFAULT_CODEGEN_CONFIG.folderNameCasing,
    typeNameCasing:
      flagsTypeCasing(flags) ??
      envTypeCasing(env.EELZAP_CODEGEN_TYPE_CASING) ??
      fileConfig.typeNameCasing ??
      DEFAULT_CODEGEN_CONFIG.typeNameCasing,
    addFieldComments:
      flags.addFieldComments ??
      envBoolean(env.EELZAP_CODEGEN_ADD_FIELD_COMMENTS) ??
      fileConfig.addFieldComments ??
      DEFAULT_CODEGEN_CONFIG.addFieldComments,
    generateIndex:
      flags.generateIndex ??
      envBoolean(env.EELZAP_CODEGEN_GENERATE_INDEX) ??
      fileConfig.generateIndex ??
      DEFAULT_CODEGEN_CONFIG.generateIndex,
    includeSeo:
      flags.includeSeo ??
      envBoolean(env.EELZAP_CODEGEN_INCLUDE_SEO) ??
      fileConfig.includeSeo ??
      DEFAULT_CODEGEN_CONFIG.includeSeo,
    includeMeta:
      flags.includeMeta ??
      envBoolean(env.EELZAP_CODEGEN_INCLUDE_META) ??
      fileConfig.includeMeta ??
      DEFAULT_CODEGEN_CONFIG.includeMeta,
    header: fileConfig.header ?? DEFAULT_CODEGEN_CONFIG.header,
    client: fileConfig.client,
  };
}

function parseJsonConfig(raw: string, filePath: string): EelZapCodegenConfig {
  try {
    return JSON.parse(raw) as EelZapCodegenConfig;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Invalid JSON.';
    throw new Error(`Failed to parse config file ${filePath}: ${message}`);
  }
}

function parseTypeScriptConfig(raw: string, filePath: string): EelZapCodegenConfig {
  const transformed = raw
    .replace(/^import\s+type\s+[^;]+;$/gm, '')
    .replace(/\s+satisfies\s+[^;]+(?=;)/g, '')
    .replace(/^export\s+default/m, 'module.exports =');

  try {
    const script = new Script(transformed, { filename: filePath });
    const module = { exports: {} as EelZapCodegenConfig };
    script.runInNewContext({
      module,
      exports: module.exports,
      process,
      console,
    });
    return module.exports;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Invalid TypeScript config.';
    throw new Error(`Failed to parse config file ${filePath}: ${message}`);
  }
}

function normalizeStringArray(values?: string[]): string[] {
  if (!values) {
    return [];
  }

  return [...new Set(values.map((value) => value.trim()).filter(Boolean))];
}

function envList(value?: string): string[] | undefined {
  if (!value) {
    return undefined;
  }

  return value
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function envBoolean(value?: string): boolean | undefined {
  if (value === undefined) {
    return undefined;
  }

  if (value === 'true') {
    return true;
  }

  if (value === 'false') {
    return false;
  }

  return undefined;
}

function envFileCasing(value?: string): FileNameCasing | undefined {
  if (value === 'kebab' || value === 'camel' || value === 'pascal' || value === 'snake') {
    return value;
  }

  return undefined;
}

function envTypeCasing(value?: string): TypeNameCasing | undefined {
  if (value === 'camel' || value === 'pascal') {
    return value;
  }

  return undefined;
}

function flagsCasing(
  _flags: CliFlags,
  _key: 'fileNameCasing' | 'folderNameCasing',
): FileNameCasing | undefined {
  return undefined;
}

function flagsTypeCasing(_flags: CliFlags): TypeNameCasing | undefined {
  return undefined;
}
